### PR TITLE
Map

### PR DESCRIPTION
**Pull request by victoriapalacios**
@bhennes2  Still working on styles, but was just curious, does the filter drop down work for you? I can't seem to make it work.

### CODE REVIEW

**Comment by bhennes2** [comment]
@victoriapalacios I didn't wire that up quite yet. Would it help if I did that for you and then let you style it?

**Comment by victoriapalacios** [comment]
@bhennes2 no blockers on my end, just curious!

**Comment by victoriapalacios** [comment]
@bhennes2 Take a look at the styles I have here now. I didn't want to stray too far away from their current site branding, let me know thoughts.

**Comment by victoriapalacios** [comment]
@bhennes2 check out style changes here.

**Comment by bhennes2** [comment]
We're going to close this PR and open another one with no merge conflicts.

**Pull request closed without merging**
